job: cim_rl_workflow
scenario_path: "cim"
log_path: "logs/cim.txt"
main:
  num_episodes: 1 # Number of episodes to run. Each episode is one cycle of roll-out and training.
  num_steps: null
  eval_schedule: 1
  logging:
    stdout: INFO
    file: DEBUG
rollout:
  logging:
    stdout: INFO
    file: DEBUG
training:
  mode: simple
  load_path: null
  load_episode: null
  checkpointing:
    path: "checkpoints"
    interval: 5
  logging:
    stdout: INFO
    file: DEBUG
